### ISSUE TITLE
v1.9.1 unable to install in visual studio 2015

### ISSUE THREAD

**Issue by wmjdgla** [stkb/Rewrap#101]
Double clicking on the vsix file produced the error "This extension is not installable on any currently installed products."

The install log shows:
...
Supported Products:
	Microsoft.VisualStudio.Code
		Version : 
...
No other supported products are listed.

**Comment by stkb** [comment]
It looks like you were trying to install the VSCode version? I just tried installing v1.10.0 from within VS 2015 and it installed fine. Since this is so old I will close it
