### ISSUE TITLE
Prolog support

### ISSUE THREAD

**Issue by acmiyaguchi** [stkb/Rewrap#104]
The extension currently does not support comments in Prolog. 

Swi-Prolog supports [two flavors of commenting](http://www.swi-prolog.org/pldoc/man?section=pldoc-comments): single line comments with `%` and block comments with `/* ... */`. The file extension is generally `.pl`.

**Comment by bradleyayers** [comment]
@acmiyaguchi would you mind opening a PR to add support to Rewrap? I'd love Rewrap to support prolog.

**Comment by acmiyaguchi** [comment]
@bradleyayers Yep, I've had #105 open for a while now. See the linked PR below the issue.
