### ISSUE TITLE
Rewrap not respecting comments in my language

### ISSUE THREAD

**Issue by dkyleward** [stkb/Rewrap#111]
I'm using a specialized language that we've built a VSCode extension for. The syntax highlighting respects comments (lines starting with "//") and pressing ctrl+k+c comments the code correctly. However, when I press alt+q to reflow/wrap the comment, it breaks in the following way:

```
// the first half of a very long comment and then the
end
```

Is there something missing in my language extension? It works perfectly in R scripts and other languages.

Thanks for the help!

**Comment by stkb** [comment]
This should now be fixed in v1.10.0. Since this is so sold I am closing
