### ISSUE TITLE
Spaces incorrrectly removed before double quotes

### ISSUE THREAD

**Issue by JohnRusk** [stkb/Rewrap#114]
When using Rewrap on a markdown file, I noticed that it took out spaces in front of double quotes.  

BTW These were the open-quotes character (“) not the symmetrical/generic double quotes character (").

E.g. this
```then choose “Purchase”.```
became this
```then choose“Purchase”.```

**Comment by stkb** [comment]
Closing as dup of #119. Fix is on the way
