### ISSUE TITLE
Autowrap is weird, needs more love

### ISSUE THREAD

**Issue by thany** [stkb/Rewrap#117]
Autowrap feel really weird. It seems to work okay when just typing a comment, but what about comments that are already >80 characters long? When changing such comment, it only wraps when typing a space. This feels arbitrary. Why not wrap as soon as neccesary?

To autowrap a comment that is already too long, I have to type that arbitrary space at the end to make autowrap do its thing. That's what we call "manual" - the opposite of auto 🙂

Consider this:
```javascript
// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a varius
// lectus. Morbi vel nulla ac felis condimentum interdum. Nullam at ex molestie,
// malesuada dolor ut, vehicula nisl. 
```
Try typing after the word "varius". It doesn't re-wrap comments that are already spanning multiple lines, when typing at the end of the first line. It wraps, but the the line(s) after stay as they are. This just feels very beta to me.

I would also expect it to autowrap comments on saving the document.

I would also expect it to autowrap when pasting.

**Comment by Y0hy0h** [comment]
I agree that auto-wrap behaves non-intuitively. It should be equivalent to executing <kbd>Alt</kbd>+<kbd>Q</kbd> after every keystroke. This means that it should check whether the current line overflows and if it does, it should reformat the entire paragraph just like <kbd>Alt</kbd>+<kbd>Q</kbd>.

I guess that the current behavior is done to minimize magic, but it does not feel right.

As for whether rewrap should execute on save and paste, I think those should be separate issues/settings.

**Comment by ELLIOTTCABLE** [comment]
I disagree with @Y0hy0h, in that I very-appreciate the non-magic spirit of the behaviour, but I agree with @thany in that I think it could still be improved.

A middle-ground that jumps out to me as ideal — i.e. still doesn't mess with formatting elsewhere in the comment or docblock, but is more ‘intuitive’ — is to autowrap *the rest of the paragraph* when the cursor crosses the column-barrier.

#### Input, configured to wrap to column 40, cursor is ⁁

```
(** Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    Lorem Ipsum has been the industry's⁁
    standard dummy text ever since the
    1500s, when an unknown printer took
    a galley of type and scrambled it to
    make a type specimen book.

    It has survived not only five centuries, but also the leap into electronic
    typesetting, remaining essentially unchanged. It was popularised in the
    1960s with the release of Letraset sheets containing Lorem Ipsum passages,
    and more recently with desktop publishing software like Aldus PageMaker
    including versions of Lorem Ipsum. *)
```

#### After typing "␣HELLO"


```
(** Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    Lorem Ipsum has been the industry's
    HELLO⁁ standard dummy text ever since
    the 1500s, when an unknown printer
    took a galley of type and scrambled
    it to make a type specimen book.

    It has survived not only five centuries, but also the leap into electronic
    typesetting, remaining essentially unchanged. It was popularised in the
    1960s with the release of Letraset sheets containing Lorem Ipsum passages,
    and more recently with desktop publishing software like Aldus PageMaker
    including versions of Lorem Ipsum. *)
```

Notice, the atmospheric formatting hasn't been "fixed" (read: fucked with); but the section that the user just conceptually *changed*, has continued to be consistent as they edit.

Thoughts?

**Comment by stkb** [comment]
Auto-wrap was designed to emulate [Emacs auto fill mode](https://ftp.gnu.org/old-gnu/Manuals/emacs-20.7/html_node/emacs_213.html) and that's still how it works. Having the whole paragraph reflow the whole time is still a desire (#65), but there have just always been issues with a higher priority. Closing this issue in favor of that one.
