### ISSUE TITLE
Bug: spaces before and after quotes (U+201C and U+201D) removed

### ISSUE THREAD

**Issue by michael-brade** [stkb/Rewrap#119]
This is probably one of my most essential VS Code extensions :-) I use it a lot.

The problem: when writing LaTeX, I use the `csquotes` package and “ and ” as active quotes.
If I rewrap a paragraph of text where a word in “quotes” (like this) happens to be at the end of a line, rewrap removes the space and creates
```
a word in“quotes”
```
instead--provided that the line breaks just after the last closing quote or, if it is a longer quote, after the first word in the quote.

**Comment by stkb** [comment]
Sorry I'm having trouble reproducing this. If you're still interested in seeing this fixed (and I know it's been a while), I'll need an exact piece of text that demonstrates the problem.

**Comment by michael-brade** [comment]
Yes, of course I am still interested :-) I am using this constantly.

To reproduce: set the "Editor: Word Wrap Column" to 120 and set "Editor: Word Wrap" to `wordWrapColumn`.

The use this text:
```
This is a paragraph test text test text test text test text test text test text test text test text test text test “text”
test text test text test text test text test text test text test text test text test text test text test text 
```
And rewrap it. The space before “ will be gone.

**Comment by stkb** [comment]
Thanks! I can reproduce and now understand the problem. It's related to CJK-language support so I need to find a fix without breaking anything there.

**Comment by stkb** [comment]
This was finally added in v1.15.0. It should be working now

**Comment by michael-brade** [comment]
Sorry that I didn't answer yet. It is working perfectly and I am using it regularly :-) Thanks a lot!

**Comment by stkb** [comment]
@michael-brade good to hear, thanks :)
