### ISSUE TITLE
doesn't work with .pylintrc file

### ISSUE THREAD

**Issue by dmig** [stkb/Rewrap#121]
I'm trying this plugin on `.pylintrc` with a very long line. But `wrap at column` command does nothing.

Here is the file: https://gist.github.com/dmig/abcc4edd3cbf621c5bae1b00513434c4

**Comment by stkb** [comment]
This is now in [pre-release version 17.6](https://github.com/stkb/Rewrap/releases/tag/beta)

**Comment by stkb** [comment]
Now also in stable v1.16.2
