### ISSUE TITLE
Add support for Julia

### ISSUE THREAD

**Issue by kbarros** [stkb/Rewrap#137]
I think Julia support can more or less copy Python. Comments are start with `#`, and Julia also supports multiline strings with `""" <str> """` and `r""" <raw_str> """`

**Comment by gyk** [comment]
Manually adding the following code to `/Users/$USER/.vscode/extensions/stkb.rewrap-$VERSION/vscode/compiled/Core/Parsing.Documents.js` works for me:

```js
lang("Julia", "", ".jl", (() => {
  const commentParsers_ = (0, _List.ofArray)([(0, _Parsing2.block)(["#=", "=#"]), (0, _Parsing2.line)("#"), (0, _Parsing2.block)(["r?\"\"\"", "\"\"\""])]);
  return (0, _CurriedLambda2.default)(function (settings_) {
      return (0, _Parsing2.sourceCode)(commentParsers_, settings_);
});
})())
```

**Comment by stkb** [comment]
This is now in v1.11.0
