### ISSUE TITLE
Disable autowrap when wordwrap is not off

### ISSUE THREAD

**Issue by memeplex** [stkb/Rewrap#142]
For some languages I want soft wrapping (LaTeX, Markdown), for the rest I don't. Now, autowrap is a global toggle. At least disable it when soft wrap is enabled so that it doesn't interfere with normal vscode wrapping.

**Comment by DrDeb** [comment]
Please don't, I use both at the same time. Having autowrap not be a global setting would be the right solution.

**Comment by stkb** [comment]
In the next release auto-wrap can be set per language https://github.com/stkb/Rewrap/issues/149#issuecomment-677708171, which yes hopefully is the better solution. I'll close this in favor of that.
