### ISSUE TITLE
v1.9.2 unable to install in Visual Studio 2019.16.1.0

### ISSUE THREAD

**Issue by sburgett** [stkb/Rewrap#143]
Double clicking on the vsix file produced the following error:

> **Install Failed**
> The install of 'Rewrap' was not successful for all the selected products. For more information, click on the install log link at the bottom of the dialog.
> 
> **Rewrap**
> This extension is not installable on any currently installed products.

Install log and Visual Studio info attached:
[dd_VSIXInstaller_20190524105827.log](https://github.com/stkb/Rewrap/files/3218082/dd_VSIXInstaller_20190524105827.log)
[Visual Studio Info.txt](https://github.com/stkb/Rewrap/files/3218083/Visual.Studio.Info.txt)

**Comment by stkb** [comment]
Hi, sorry about this and thanks for the catch.

This had me stumped for a little while, but I found out that MS had changed their policy when it comes to Visual Studio version numbers with VS2019. So while VS2017 stayed at v15.0.x.x throughout its lifetime, VS2019 updated from 16.0 to 16.1, which broke the supported version range for the extension.

I've published the fixed version (v1.9.3) to [the marketplace](https://marketplace.visualstudio.com/items?itemName=stkb.Rewrap-18980). Let me know if you're still having issues installing.
