### ISSUE TITLE
Ignore Markdown code blocks

### ISSUE THREAD

**Issue by SeanDS** [stkb/Rewrap#152]
Maybe I'm doing something silly, but I've got a Markdown document with code blocks and the code is getting wrapped when I run rewrap.

```markdown
here is some code:

.. code-block:: python

   x = 1 + 2 # some very long line that should not be wrapped... some very long line that should not be wrapped... some very long line that should not be wrapped...
```

If I select all with `Ctrl + A` and then perform wrapping with `Alt + Q`, the code block gets wrapped:
```markdown
.. code-block:: python

   x = 1 + 2 # some very long line that should not be wrapped... some very long line that should not
   be wrapped... some very long line that should not be wrapped...
```

Obviously code blocks and other preformatted text must not be wrapped. Is there a way to prevent this behaviour?

**Comment by rossmacarthur** [comment]
As far as a know directives like 

```
.. code-block:: python
```

Are reStructuredText syntax not in Markdown. It looks like this project doesn't yet support reStructuredText.

**Comment by SeanDS** [comment]
Ah you're right. Then it's probably doing what it should do given it doesn't know it's reStructuredText. Thanks for pointing that out - I'll close this.
