### ISSUE TITLE
Bug (python): rewrap indents text incorrectly with open multi-line string

### ISSUE THREAD

**Issue by adrn** [stkb/Rewrap#157]
VSCode v1.35.1
rewrap v1.9.1

I haven't fully figured this out, but I've found a way to reproduce it: create a python module with the following
```python
def func():
    docstr = """stuff
    """
    a = 0

# Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text
```
Select the comment line, and rewrap, this produces:
```python
def func():
    docstr = """stuff
    """
    a = 5

    # Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text
```
i.e., it indents the comment line incorrectly and does not wrap it. I would expect something like (for an 80 character line wrap):
```python
def func():
    docstr = """stuff
    """
    a = 5

# Here is a bunch of text Here is a bunch of text Here is a bunch of text Here
# is a bunch of text Here is a bunch of text Here is a bunch of text Here is a
# bunch of text
```

If you remove the multi-line aspect of the string in the function, everything works fine. So, if instead you start with:
```python
def func():
    docstr = """stuff"""
    a = 5

# Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text Here is a bunch of text
```
and rewrap the last comment line, it works as expected.

**Comment by stkb** [comment]
Ok the fix is now in master and will be in the next release. If you want you can get it early by [downloading the latest beta version](https://github.com/stkb/Rewrap/releases/tag/beta).

**Comment by stkb** [comment]
1.12.0 is now released. Should be fixed so closing...
