### ISSUE TITLE
Default key to be Alt+Q messes up Mac users experience

### ISSUE THREAD

**Issue by TakCastel** [stkb/Rewrap#158]
Hello,

For MacOS users, `cmd+Q` is for closing the window. 

The key by default to wrap text being `Alt+Q` is **really** close to this shortcut. 

Have you considered going back to `Alt+K` or something less similar to this Mac command ?

Thank you very much :)

**Comment by marco-m** [comment]
I have a mac and got bitten a few times by this, but I still think that the default key should stay Alt+Q to keep things simple and uniform (I think that this key sequence comes from Emacs). If you use often enough this extension, it becomes muscle memory and the problem goes away.

If you want to change the key binding for you, the Rewrap wiki explains how: [Keybindings-VSCode](https://github.com/stkb/Rewrap/wiki/Keybindings-VSCode)
