### ISSUE TITLE
Alt + Q "Index was outside of the bounds of the array"

### ISSUE THREAD

**Issue by aancag** [stkb/Rewrap#159]
Using the Alt+Q combination on a empty line results in an error "Index was outside of the bounds of the array"

100% reproducibile

Rewrap Version 1.9.3, Visual studio Proffesional 2015

![image](https://user-images.githubusercontent.com/4345884/62354775-47cc7380-b516-11e9-88d6-63fd8deda1d4.png)

**Comment by stkb** [comment]
This should hopefully now be fixed in v1.11.0
