### ISSUE TITLE
Comment wrapping broken in .jsonc files

### ISSUE THREAD

**Issue by uinerd** [stkb/Rewrap#160]
In VS Code editing a jsonc (JSON with comments) file, comment wrapping is broken.

**example.jsonc:**
**//** So here is a really long comment that should illustrate the problem I'm seeing in Rewrap. Of course this line is unusually long.
**//** Here's a second line that is part of the comment block.

**Alt-q does this:**
**//** So here is a really long comment that should illustrate the problem I'm
seeing in Rewrap. Of course this line is unusually long. **//** Here's a second line
that is part of the comment block.

**Comment by stkb** [comment]
Fixed in 1.10.1
