### ISSUE TITLE
Auto-wrap in Vue Single File Components (SFCs)

### ISSUE THREAD

**Issue by scriptcoded** [stkb/Rewrap#162]
First of all, wonderful extension. It saves a huge amount of time that's usually wasted on formatting!

It seems that while wrapping is supported in Vue SFCs (#82), autoWrap isn't. I hope this is an easy fix.

Another, more generic way of tackling this might be to add some form of language list that could be configured in the settings. In that way any language could be used. I must admit that I haven't looked at the code, so I don't know the scope of this change, but it might be an alternative solution.

Thanks,
Malcolm

**Comment by stkb** [comment]
I am looking at this, but it has me a little stumped at the moment. Will take a little time to work out why it's not working

**Comment by stkb** [comment]
I believe I've fixed this and it will be in the next release, this weekend. If you prefer you can download [the latest beta version](https://github.com/stkb/Rewrap/releases/tag/beta) now which contains the fix.

**Comment by scriptcoded** [comment]
@stkb Wonderful! I'll see if I find some time to check it out!

**Comment by stkb** [comment]
v1.11.1 now released
