### ISSUE TITLE
Does not work well with embeded<see cref="TYPE"/>

### ISSUE THREAD

**Issue by neolib** [stkb/Rewrap#174]
I like this Extension! But I found a small problem. It seems Rerwap does not handle &lt;see cref="TYPE"/&gt; well in mult-line comments; it either does not move &lt;see&gt; block or treat it as a whole word.

For example:
```
/// <remarks>
/// The reason to create a separate class instead of <see
/// cref="List{string}"/>
/// for field vlaues is that the List indexer would throw exception on
/// accessing a value out of bound. This class has a custom indexer that
/// simply returns null in this situation and at the same time caller can
/// check the
/// <see cref="FieldCount"/> property to get actual number of fields in this
/// record. The benefit is that caller won't worry about indexing
/// exceptions; and this is very convenient for reading malformed CSV
/// content because all records may not have exactly the same number of
/// fields.
/// </remarks>
```

**Comment by stkb** [comment]
This now works much better in v1.12.0. The 2nd `<see ...` tag in the example will now be wrapped onto the line above. Unfortunately the line-break after the first `<see />` tag is still kept. That will take more time to fix and I've created #211 for that issue.
