### ISSUE TITLE
Make autowrap a workspace setting

### ISSUE THREAD

**Issue by ghost** [stkb/Rewrap#176]
There's no need for the setting `rewrap.autoWrap.enabled` to have `application` scope as it does currently (2c927ab24988f20d625282b94568ccd46e4f502c).

I personally use Rewrap for a single workspace only. It would also help with issues #92 and #142.

**Comment by stkb** [comment]
Will be a workspace/language-overridable setting in the next release (https://github.com/stkb/Rewrap/issues/149#issuecomment-677708171). Closing as dup
