### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by PaltryProgrammer** [stkb/Rewrap#179]
I received the error message below upon attempting to install. I do not have Visual Studio Code installed however I do have Visual Studio 2019 installed. I do not see any reference to "Rewrap" via Tools->Options Please advise. Thank You Kindly Cheerios
error message: "One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code."
PS Would it be possible for your extension to be rewritten so as to automatically wrap comments to the current editor window width upon resizing of the window? That would be most convenient.

**Comment by stkb** [comment]
It sounds like you were trying to install with a downloaded file of the VSCode version.

To install in Visual Studio 2019, it's best to go to _Extensions -> Manage Extensions_, and search for "Rewrap" in the Online section there.

About your second point, Rewrap is really only a hard wrapper. To soft-wrap based on the window width, you can use [Visual Studio's own option](https://docs.microsoft.com/en-us/visualstudio/ide/reference/how-to-manage-word-wrap-in-the-editor?view=vs-2019)
