### ISSUE TITLE
Feature Request: Support ROxygen comments for R

### ISSUE THREAD

**Issue by christiantillich** [stkb/Rewrap#181]
Rewrap works as desired if I'm using the comment token "#". However, there are several occasions where the comment token needs to be "#'". ROxygen comments and comments for knitr::spin() come to mind. When using these comments, reflow takes this...

#' This is my long comment string

...and does this...

#' This is my long
#comment string

It just treats the ' mark as the start of the text, instead of part of the comment token.

**Comment by stkb** [comment]
Hi, the proper handling of the `'` character is easy and will be in the next release. I would like to support ROxygen syntax fully too but that's rather more involved.

**Comment by stkb** [comment]
v1.11.0 now handles the ' characters correctly

**Comment by christiantillich** [comment]
Great news! Thanks a bunch!
