### ISSUE TITLE
Feature Request: Add Fortran 90 as supported language

### ISSUE THREAD

**Issue by llamm-de** [stkb/Rewrap#185]
When using Rewrap on .f90, .f95, .f08 files, add a continuation mark "&" at the end of the line which is wrapped to the next line.

**Comment by stkb** [comment]
As a side note, Rewrap should now work for comments in Fortran, if you have a Fortran extension installed in VSCode.

About your specific request, while I don't knwo much about Fortran, I don't really want to get into code formatting/line splitting. I feel that's something more suited to a language-specific extension.

**Comment by stkb** [comment]
I'm going to close this as, while this is a simple example, I don't think Rewrap should support source code formatting (it's enough to have to support documentation formatting).
