### ISSUE TITLE
Feature request: Adding support for Racket

### ISSUE THREAD

**Issue by AlexandreGaubil** [stkb/Rewrap#187]
Currently, Rewrap treats Racket as a text file, which generates problems with comments and leads to badly formatted code. Adding support for Racket would be great.

**Comment by stkb** [comment]
Hi, this should now work in the latest version (1.10.0), if you have one of the Racket extensions installed in VSCode.

**Comment by stkb** [comment]
Closing... assuming fixed (please comment if not)
