### ISSUE TITLE
rST support impacts non-comment hard wrapping

### ISSUE THREAD

**Issue by cbush** [stkb/Rewrap#191]
First of all, thank you for the great extension! I have tried other hard wrapping extensions, but they don't even come close to Rewrap.

We have been using Rewrap in VS Code to hard wrap blocks of text _that aren't comments_ in rST documents. With the latest release that adds support for rST if we have the rST extension, rewrap functionality is now limited to actual rST comments (i.e. `.. lines that look like this`). This means to continue using Rewrap to hard wrap regular blocks of text, I have to uninstall the rST extension or treat my rST files as plaintext, which means losing syntax highlighting and other features.

Is there a way to have Rewrap ignore a certain language's extension or otherwise operate on blocks that aren't comments?

Thank you!

**Comment by stkb** [comment]
That's no good! I've added an exception to put it back to how it was for rST. The next release will be out this weekend.

I still need to support rST fully (#88). I'll try to get on to that.

Thanks for the kind words

**Comment by stkb** [comment]
v1.10.1 has now been released.

**Comment by ewjoachim** [comment]
Thanks for the speedy fix ! Just checked, it works now.

**Comment by cbush** [comment]
Thank you so much!

**Comment by melissamahoney-mongodb** [comment]
Exactly what I needed, thank you!!
