### ISSUE TITLE
Incorrect F# dependencies in 1.10 vsix (Visual Studio)

### ISSUE THREAD

**Issue by EuroMic** [stkb/Rewrap#195]
Rewrap 1.10 fails to load (Visual Studio 2017) with an error stating that FSharp.Core.dll 4.7 could not be found. I'm unable to test with Visual Studio 2019 at this time.

The Rewrap.Core.dll that is packaged in the current vsix package (downloaded from either https://marketplace.visualstudio.com/_apis/public/gallery/publishers/stkb/vsextensions/Rewrap-18980/1.10.0/vspackage or from VS 2017 Extensions and Updates) has a dependency on FSharp.Core.dll 4.7, but the .vsix package ships with FSharp.Core.dll 4.6

ILDASM for Rewrap.Core.dll:
.assembly extern FSharp.Core
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:7:0:0
}

ILDASM for FSharp.Core:
.assembly FSharp.Core
{
  .ver 4:6:0:0
}

**Comment by EuroMic** [comment]
For completeness, here's the Visual Studio 2017 ActivityLog.xml error message:

System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Rewrap.Core.languageNameForFile(File file)
   at VS.Options.OptionsPage.GetOptions(File file)
   at VS.Editor.GetSettings(IWpfTextView textView, Func`2 getColumn)
   at VS.Editor.AutoWrap(IWpfTextView textView, Int32 pos, String newText)
   at VS.AutoWrapCommand.<>c__DisplayClass8_0.<AttachToTextView>g__TextBuffer_Changed|0(Object sender, TextContentChangedEventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by nvpbrown** [comment]
I am seeing the same issue on Visual Studio Professional 2019.

**Comment by stkb** [comment]
Thanks guys and sorry about that. Could you try installing from this updated.
vsix file? (you have to rename it from .zip to .vsix) I think I have the dependencies straight now.

[Rewrap.VS.1.10.1.zip](https://github.com/stkb/Rewrap/files/4639849/Rewrap.VS.1.10.1.zip)

**Comment by nvpbrown** [comment]
Yes, this works.

**Comment by stkb** [comment]
v1.10.1 has now been released.

**Comment by EuroMic** [comment]
I confirmed that v1.10.1 fixes the issue on VS 2017 as well. Thank you!
