### ISSUE TITLE
Nothing happens when using command

### ISSUE THREAD

**Issue by ewjoachim** [stkb/Rewrap#196]
This plugin has been working fine for months. When I opened my editor this morning it wasn't working anymore (a.k.a nothing happens when I press alt+q or use the command from the cmd+shift+p menu). Not sure what exactly would be appropriate information to help you figure out what is happening, so here's what I can think of:

- Plugin version: 1.10.0 (which is apparently 4 days old so that could be what changed, but doesn't tell us why it failed)
- VScode: 1.45.1 (latest)
- On: macos Catalina 10.15.4
- File format: restructuretext (https://github.com/peopledoc/procrastinate/blob/master/docs/discussions.rst)
- Relevant settings:
```json
    "editor.rulers": [
        88
    ],
    "[restructuredtext]": {
        "editor.tabSize": 4
    }
```
- Debug console: empty

Any idea ?

**Comment by stkb** [comment]
Hi, it sounds like you're affected by #191 for reStructuredText. If you try some other types of files it should still work. I'm just wrapping up the release that has the fix for that; it should be available in a couple of hours.

**Comment by ewjoachim** [comment]
Ah, indeed, I just checks and Python docstrings are still wrapped.

Closing as dusplicate, will reopen if the release doesn't fix my case.

**Comment by jchesterpivotal** [comment]
Sorry for necrothreading, but I've had the same experience with asciidoc.

Only started in the last few days and doesn't seem to be fixed by 1.10.1.

**Comment by stkb** [comment]
@jchesterpivotal No problem. The fix is in master and will be in the next release, probably this weekend. If you don't want to wait you can [install the latest beta version](https://github.com/stkb/Rewrap/releases/tag/beta)

**Comment by jchesterpivotal** [comment]
Thanks!

**Comment by jchesterpivotal** [comment]
I can confirm that it's fixed for me.

**Comment by stkb** [comment]
@jchesterpivotal thanks!
