### ISSUE TITLE
Updating wrappingColumn requires restarting VSCode to take effect

### ISSUE THREAD

**Issue by GreenGremlin** [stkb/Rewrap#197]
Updating the `rewrap.wrappingColumn` setting seems to take a restart of VSCode to take effect. It seems that updating a setting for an extension should not require restarting the editor.

**Comment by stkb** [comment]
Duplicate of #99 (a fix is on the way)

**Comment by stkb** [comment]
See https://github.com/stkb/Rewrap/issues/99#issuecomment-632027290
