### ISSUE TITLE
VS Code reports that setting is not supported in per-language configuration

### ISSUE THREAD

**Issue by louridas** [stkb/Rewrap#200]
Hello,

I am setting `rewrap.wrappingColumn` in a particular language (`[latex]`). Although the setting works, when I open `settings.json` it reports the problem:

"This setting does not support per-language configuration."

Although it does not affect the functionality of the setting, as it does work as expected, it would be nice not to have the warning displayed.

**Comment by stkb** [comment]
Thanks for the catch! This was new since I last looked; the settings are now declared correctly as per-language. The fixed version will come out this weekend

**Comment by stkb** [comment]
v1.11.1 now released
