### ISSUE TITLE
dotenv (.env) not supported correctly

### ISSUE THREAD

**Issue by aschmois** [stkb/Rewrap#201]
Comments inside of a dotenv file don't wrap correctly. When wrapping a line the `#` is not added automatically. And sometimes will try to wrap non commented lines as well.

**Comment by stkb** [comment]
Hi, this should now work correctly if you have a dotenv language extension installed in VSCode, eg mikestead.dotenv (I just tried it myself)

**Comment by aschmois** [comment]
On newest version 1.11.1

![image](https://user-images.githubusercontent.com/4064285/83358826-27db2b80-a344-11ea-84c4-97acebbc202e.png)
Running rewrap on the long line produces:
![image](https://user-images.githubusercontent.com/4064285/83358836-3a556500-a344-11ea-857d-4bf13db0a075.png)
Running rewrap on the short line produces:
![image](https://user-images.githubusercontent.com/4064285/83358852-5953f700-a344-11ea-9ebb-b43ba429b86b.png)

**Comment by stkb** [comment]
Do you have the mikestead.dotenv extension installed?
Please otherwise go to Help -> Toggle Developer Tools and then the Console, and see if there are any related errors.

**Comment by aschmois** [comment]
> Do you have the mikestead.dotenv extension installed?
Yep
> Please otherwise go to Help -> Toggle Developer Tools and then the Console, and see if there are any related errors.
No errors appear when rewrapping.

One note: I am running this through ssh remote workspace. However everything else seems to work fine.

**Comment by stkb** [comment]
> One note: I am running this through ssh remote workspace. However everything else seems to work fine.

Ok I think that's why it's not finding the extension. Any chance you can test it just locally?

**Comment by aschmois** [comment]
It does work locally, I guess the issue really is on `DotENV` since it should be an ssh compatible extension like rewrap is. My only concern is that maybe rewrap shouldn't solely rely on other extensions for comment support? Something like `DotENV` is nice to have for syntax highlighting but I can see a lot of users not installing this extension often since it's not a common ocurrence to edit `DotENV` files.

Saying that though I haven't looked into the source for rewrap so I can't make assumptions on how it structures what is and what isn't a comment. Any workarounds that you know of or just kind of stuck waiting for `DotEnv` to support installing into ssh?

**Comment by aschmois** [comment]
On the note of installed extensions, does vscode not abstract away a list of installed extensions regardless if they're loaded on the client or the server it's connected to? I would have thought they merged at one point.

**Comment by stkb** [comment]
Fixed in v1.14.0
