### ISSUE TITLE
Julia docstring wrapping broken in 1.10

### ISSUE THREAD

**Issue by marius311** [stkb/Rewrap#203]
Docstrings in Julia look like 

```julia
doc"""
... 
"""
```

The presence of the `doc` part breaks rewrap for the remainder of the document, and I can't get anything to wrap, even if I just select a line explicitly before invoking the command. This was working in 1.9.1 but is broken in all of the 1.10 releases (I'm checking with vscode 1.45.1)

**Comment by stkb** [comment]
Hi, do you mean `@doc` with a `@`? I'm not familiar with Julia, and all I can find references to in the documentation are the forms 
``` julia
@doc """
...
"""
```
and
``` julia
@doc raw"""
...
"""
```

**Comment by marius311** [comment]
Yea sorry I over-simplified it. For a _docstring_, the `@doc` will always be there because its what "attaches" the multiline string to the definition the follows it. You could also have a non-docstring multiline string which won't have the `@doc`. 

The string prefix like `raw"""` or `doc"""` _might_ be there for docstrings or multiline strings, all it does is do some preprocessing of the string (for example, `raw` turns off variable interpolation, and `doc` turns on some markdown syntax). Technically, in Julia, you can define your own string prefixes so any string prefix not just `raw` or `doc` could be there. 

In terms of what breaks Rewrap, it seems both of the forms you gave above as well as my orignal seem to.

**Comment by stkb** [comment]
Ok thanks for the explanation! This fix is now in master and will be in the next release. If you want you can get it early by [downloading the latest beta version](https://github.com/stkb/Rewrap/releases/tag/beta).

**Comment by marius311** [comment]
Great, thanks, just checked and indeed its mostly fixed in the beta. There is just one remaining issue I found which may be a general thing but will particularly affect Juila docstrings due to the convention of how they're written. Basically, by convention, the first line is an indented function signature (indendent lines are rendered as a code block in documentation), and the subsequent lines are non-indendented description. 

```julia
doc"""

    foo(x,y)

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua

"""
function foo(x,y)
...
```

But if you put your cursor on the Lorem ipsum line and trigger Rewrap, I think because its detecting that first line is indented, it will produce this:

```julia
doc"""

    foo(x,y)

    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua

"""
function foo(x,y)
```

so it requires manually unindenting the text block each time you do it.

**Comment by stkb** [comment]
Sorry I somehow missed that last comment. That's something that affects more that just this and I will fix it.

**Comment by stkb** [comment]
I've changed how indents are handled in v1.13.0. Before it would take the indent of the first line as the "base" indent and apply that to the rest of the comment. Now it takes the whole comment as-is (meaning the least-indented line becomes the "base" indent), and the case that you give, where the first line is an indented code block, is now possible.

**Comment by marius311** [comment]
Awsome, thank you! Just tried it out and look like it works, so from what I can tell everything is good with Julia docstrings, so I'll close this issue.
