### ISSUE TITLE
FR: wrap mail quoted reply with >

### ISSUE THREAD

**Issue by anatoli26** [stkb/Rewrap#204]
Hi,

A feature request to wrap a reply of an email composed in a plain-text file, e.g.

```
> A long long long line from original mail would become...
```
```
> A long long long line from
> original mail would become...
```
Say I press "Reply" to an email, then copy the contents with quoted original text to vscode, rewrap and copy it back to the mail editor (e.g. Thunderbird).

**Comment by stkb** [comment]
Hi, this is possible if the type of the file is Markdown. I actually at one point did have markdown processing for all plain text files but turned it off because it caused confusing results for some people.

In your case, if you've just done "File -> New File" (so it's called "Untitled-1" without any file extension), you can go click on the language mode ("Plain Text" in the bottom right of VSCode) and change it to "Markdown". Then it will wrap how you want.

Alternatively you can create/save the file with a **.md** extension and it will be a markdown file.

A third option is to configure VSCode to treat all ".txt" files as markdown. To do this, open a .txt file, click the "Plain Text" in the bottom right, and choose "Configure File Association for '.txt', then choose "Markdown".

Hope something here works for you.

**Comment by anatoli26** [comment]
Hi Steve,

Oh that's great! Yeah, no problem using MD.

But there I notice a strange behavior with double level of quotation. If I have a text like this:

```
On 3/6/20 00:02, Steve wrote:
> On 6/3/20 0:01 AM, Anatoli wrote:
>> Hi,
>>
>> I have a long long long long question
```

Then with the Reformat option OFF the text becomes this:

```
On 3/6/20 00:02, Steve wrote:
> On 6/3/20 0:01 AM, Anatoli wrote:
>> Hi,
>>
>>I have a long long long
>>long question
```

i.e. the wrapped line loses spaces after the greater-than signs. And with Reformat option ON, the spaces are added between the double greater-than signs on all lines:

```
On 3/6/20 00:02, Steve wrote:
> On 6/3/20 0:01 AM, Anatoli wrote:
> > Hi,
> >
> > I have a long long long
> > long question
```

Also, I notice that when there's a short line (signature), like this:

```
Regards,
Anatoli
```

When wrapping all the text, these 2 last lines become one:

```
Regards, Anatoli
```

Why is it so?

**Comment by stkb** [comment]
I'll answer your 2nd question first: to reflow a paragraph you have to cut up long lines and join short lines together, so that's what it's doing here; it doesn't know you want to keep the line-break after `Regards,`.

There are to ways around this. You can add a blank line in-between so that they are seen as two separate paragraphs:
```
Regards,

Anatoli
```
Or you can add two spaces onto the end of a line where you want to keep a line break (you can do this anywhere):
```
Regards,··
Anatoli
```
(`·` represents a space here)

---

Your first question: it may be a bug and I will investigate it.

**Comment by stkb** [comment]
Hopefully the issue should be fixed in the latest release (1.12.0). Please open another issue if you have any other problems :)

**Comment by anatoli26** [comment]
Not sure if to open a new issue, the problem was solved in 1.12.0 only partially. There are no more random spaces mixing into the comment, but all `>` got 1 space in between, e.g.:

```
>>> some deep reply
```
becomes
```
> > > some deep reply
```

when the `>>>` should stay intact.

**Comment by stkb** [comment]
Sorry, it was more complicated that I thought! I will get on to fixing that.

**Comment by stkb** [comment]
If you have time could you try the latest [beta](https://github.com/stkb/Rewrap/releases/tag/beta)? I think I have it fixed now.

**Comment by anatoli26** [comment]
Hi Steve,

Just tested the beta.

The following text:

```
>>>>>>
>>>>>> On 15/6/20 18:47, John Doe wrote:
>>>>>>> Lorem ipsum dolor sit amet,
>>>>>>>
>>>>>>> Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
>>>>>>>
>>>>>>> Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris. Integer in mauris eu nibh euismod gravida.
>>>>>>>
>>>>>>> Duis ac tellus et risus vulputate vehicula. Donec lobortis risus a elit. Etiam tempor. Ut ullamcorper, ligula eu tempor congue, eros est euismod turpis, id tincidunt sapien risus a quam. Maecenas fermentum consequat mi. Donec fermentum. Pellentesque malesuada nulla a mi.
>>>>>>>
>>>>>>> Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque.
>>>>>>>
>>>>>>> -- 
>>>>>>> Thanks,
>>>>>>>
>>>>>>> John Doe  
>>>>>>> ACME Inc
```

becomes this:

```
>>>>>>
>>>>>> On 15/6/20 18:47, John Doe wrote:
>>>>>>> Lorem ipsum dolor sit amet,
>>>>>>>
>>>>>>> Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
>>>>>>>et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
>>>>>>>exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
>>>>>>>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
>>>>>>>dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
>>>>>>>proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
>>>>>>>
>>>>>>> Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam
>>>>>>>varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus
>>>>>>>magna felis sollicitudin mauris. Integer in mauris eu nibh euismod
>>>>>>>gravida.
>>>>>>>
>>>>>>> Duis ac tellus et risus vulputate vehicula. Donec lobortis risus a elit.
>>>>>>>Etiam tempor. Ut ullamcorper, ligula eu tempor congue, eros est euismod
>>>>>>>turpis, id tincidunt sapien risus a quam. Maecenas fermentum consequat
>>>>>>>mi. Donec fermentum. Pellentesque malesuada nulla a mi.
>>>>>>>
>>>>>>> Duis sapien sem, aliquet nec, commodo eget, consequat quis, neque.
>>>>>>>
>>>>>>> -- 
>>>>>>> Thanks,
>>>>>>>
>>>>>>> John Doe  
>>>>>>> ACME Inc
```

I.e. now the 2nd line in each paragraph loses a required space at the beginning after `>`. I.e. it should be:

```
>>>>>>> Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
>>>>>>> et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
```

but it is:

```
>>>>>>> Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
>>>>>>>et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
```

**Comment by stkb** [comment]
Thanks for your patience. Could you give beta 2 a try? (same link as before)

**Comment by anatoli26** [comment]
Hi Steve,

Just tested the 2nd beta and it works as expected now! Great job, thanks!

Regards,
Anatoli

**Comment by stkb** [comment]
Thanks!

**Comment by stkb** [comment]
Now in v1.13.0
