### ISSUE TITLE
Octave support

### ISSUE THREAD

**Issue by daniel-molina** [stkb/Rewrap#206]
Hello,

It would be nice to have Octave support. Octave should be equivalent to Matlab but `#` is also a valid comment character. From [Octave documentation](https://octave.org/doc/v5.2.0/Single-Line-Comments.html#Single-Line-Comments):

`In the Octave language, a comment starts with either the sharp sign character, ‘#’, or the percent symbol ‘%’ and continues to the end of the line.`

 I read #72 and it seems that no support was added for `%%` in Matlab. According to [Octave style guide (Comments section)](https://wiki.octave.org/Octave_style_guide), used to develop Octave itself, I think `##`  should be wrapped too:

`Comments that start with a single sharp-sign, #, are used to explain the code on the same line as the comment itself. These comments should all be aligned to the same column to the right of the source code.`

`Comments that start with a double sharp-sign, ##, are stand-alone comments that occupy an entire line. These comments should be aligned to the same level of indentation as the code. Such comments usually describe the purpose of the following lines or the state of the program at that point. `

A note about `%!` can be found in the previous link too.

**Comment by stkb** [comment]
This is now in v1.12.0. The content of `%!` blocks is not wrapped. It would be nice to still wrap comments in those blocks though, and I've added #215 to track that feature.
