### ISSUE TITLE
Please consider publishing to Open VSX

### ISSUE THREAD

**Issue by jurisbu** [stkb/Rewrap#210]
Hi!

VSCodium users are hoping that you could publish your extension to "Open VSX" free marketplace.
Consult this blog entry: https://www.gitpod.io/blog/open-vsx/

Thanks!

**Comment by stkb** [comment]
Thanks for letting me know about that. I don't see why not :) I will look into doing it.

**Comment by stkb** [comment]
Sorry it took a while guys. It's published at https://open-vsx.org/extension/stkb/rewrap. I will close this now but I haven't tested it so please comment here if there are problems.

**Comment by Siosm** [comment]
You should also consider claiming ownership of the stkb namespace: https://github.com/eclipse/openvsx/wiki/Namespace-Access

**Comment by stkb** [comment]
@Siosm yep have already [submitted the request](https://github.com/eclipse/open-vsx.org/issues/106) :)
