### ISSUE TITLE
Not picking up editor.rulers

### ISSUE THREAD

**Issue by musm** [stkb/Rewrap#214]
I'm on v1.11.1

I've got the setting
```
  "[latex]": {
    "editor.wordWrapColumn": 100,
    "editor.wordWrap": "bounded",
    "editor.rulers": [
      100
    ],
  },
```

but for some reason executing rewrap, defaults to `80` instead of `100`

**Comment by musm** [comment]
Fixed by https://github.com/stkb/Rewrap/releases/tag/beta ?

**Comment by stkb** [comment]
@musm No you're just using plain rulers so it should work in the released version. 

Do you have `"rewrap.wrappingColumn": 80` in your settings.json (not in a language-specific section)? If so that will be taking priority.

**Comment by musm** [comment]
> Do you have `"rewrap.wrappingColumn": 80` in your settings.json (not in a language-specific section)? If so that will be taking priority.

👍  that was it, didn't even realize.

**Comment by hpfr** [comment]
Shouldn't wrapping to language- or file-specific rulers take priority over the more general , editor-wide `rewrap.wrappingColumn`? Maybe add a preference to change this behavior? I have rulers for git-commit mode that I want to override the general 88-character limit I've set, and I could imagine setting up other language-specific rulers.
