### ISSUE TITLE
Rewrap breaks when using shader language extensions

### ISSUE THREAD

**Issue by Fell** [stkb/Rewrap#217]
I'll make this one short:

When you have the shader language support extension (see below) installed, rewrap breaks and doesn't work with these files.

**The extension in question:**
https://marketplace.visualstudio.com/items?itemName=slevesque.shader
https://github.com/stef-levesque/vscode-shader

**Proposed solution:**
Treat shader code like c code, the syntax is very similar.

**Comment by stkb** [comment]
Hi, sorry there was a bug in the previous version. It should now work again with v1.13.0.

Or rather specifically, GLSL and CG files will work. HLSL (`.sf`) files still won't, because that extension doesn't provide any comment marker information for those.
