### ISSUE TITLE
Version 1.12.0 

### ISSUE THREAD

**Issue by lubrogit** [stkb/Rewrap#221]
The description claims: For any other type of file, plain-text paragraph wrapping is still supported. This is not true, eg. for extension lbi: "files.associations": { "*.LBI": "ignore"} (so that it is not cSpell-ed). The version 1.11.1 works correctly.

**Comment by stkb** [comment]
Hi, can you try the latest version v1.13.0? There was indeed a bug in v1.12.0

**Comment by stkb** [comment]
Closing as there hasn't been any more info
