### ISSUE TITLE
Set extensionKind in package.json

### ISSUE THREAD

**Issue by segevfiner** [stkb/Rewrap#231]
This extension likely only implements editor commands that don't require any file system access or the like (I'm assuming here, this needs to be verified), it can probably set:
```
"extensionKind": ["ui", "workspace"]
```
To save the need to install it in the remote workspace when using VS Code's remote development extensions.

https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location (There might be a better reference for this somewhere in VS Code's docs)

**Comment by stkb** [comment]
Thanks. I still needed to investigate working with remove workspaces to try to fix #201. With the extensionKind as `ui` everything seems to be fine. The change is in the latest [beta](https://github.com/stkb/Rewrap/releases/tag/beta).

**Comment by stkb** [comment]
Is fixed in v1.14.0
