### ISSUE TITLE
The rewrap doesn't work in .Rmd files

### ISSUE THREAD

**Issue by Andryas** [stkb/Rewrap#245]
What I need to do to allow the rewrap to work in .Rmd files?

**Comment by mihaiconstantin** [comment]
Any updates on this? I also really miss this feature and I wish to know whether there is anything that can be done here. As far as I can tell, when the [`R`](https://github.com/REditorSupport/vscode-R) extension is enabled, VSCode correctly handles `.rmd` files and knows to differentiate between the `r` script books and the markdown ones.

**Comment by stkb** [comment]
Yeah sorry I'll get on to this right away. As far as I can tell .rmd is exactly the same as a markdown document? (with a Yaml front-matter section)

**Comment by mihaiconstantin** [comment]
Thanks for taking a look at this @stkb!

Indeed, the `.rmd` document is a simple `markdown` file with a `yml` header. The only significant difference I can think of is that the code blocks have a special syntax declaration. For example, in a simple `.md` file an `r` code block would look like this:

    ```r
    # A comment.
    ```

However, within a `.rmd` the code block will look like this:

    ```{r}
    # A comment.
    ```

Often the `{r}` is extended with options, for instance:

    ```{r dev="pdf", fig.width=8, fig.height=8, out.width="200px", fig.align="center"}
    # Some code that plots something.
    ```

Would this represent a problem?

**Comment by mihaiconstantin** [comment]
> Yeah sorry I'll get on to this right away. As far as I can tell .rmd is exactly the same as a markdown document? (with a Yaml front-matter section)

Another thing is that you can also use `LaTeX` commands within an `.rmd` document. But I think `Rewrap` already plays nicely with `.tex` files.

**Comment by stkb** [comment]
Ok it's now in [pre-release version 17.6](https://github.com/stkb/Rewrap/releases/tag/beta). The code blocks shouldn't be a problem. I'm not sure about the LaTeX since Rewrap doesn't really do content-types within content-types yet

**Comment by mihaiconstantin** [comment]
Thanks a lot for adding support for `.rmd` files. I tested the pre-release on several `.rmd` files and it works really well! 
@Andryas, I think this issue can be closed?

**Comment by stkb** [comment]
@mihaiconstantin thanks, and I normally close issues once the fix is published in a stable version.

**Comment by stkb** [comment]
Now also in stable v1.16.2
