### ISSUE TITLE
Add support for Fuchsia FIDL

### ISSUE THREAD

**Issue by studgeek** [stkb/Rewrap#255]
It would be great to add support for Fuchsia FIDL. I think it's just adding the '///' for doc comments (which are in markdown also).

More details at https://fuchsia.dev/fuchsia-src/reference/fidl/language/language.

**Comment by studgeek** [comment]
Adding https://github.com/stkb/Rewrap/issues/216 would allow users to add their own support via settings as well.

**Comment by stkb** [comment]
This is now in [pre-release version 17.6](https://github.com/stkb/Rewrap/releases/tag/beta)

**Comment by stkb** [comment]
Now also in stable v1.16.2
