### ISSUE TITLE
Autowrap cannot be enabled in VS code?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [stkb/Rewrap#259]
There doesn't seem to be any way to enable autowrap in VS code: I can't find any setting for this. I have 1.14.

**Comment by adamjr27** [comment]
Same issue! Can't find [these settings](http://stkb.github.io/Rewrap/images/vsc-autowrap-settings.png) anywhere...

**Comment by stkb** [comment]
Sorry but if you're on 1.14 then I don't know why you're not seeing it 😕  What platform are you on?

**Comment by adamjr27** [comment]
Just found the settings, and it works perfectly!

On v1.14, Visual Studio Code for Windows. 

There were initially no settings found for "@ext:stkb.rewrap", but perhaps I just needed to restart or something for it to populate.

Thanks!

**Comment by PetrKryslUCSD** [comment]
Win 10.  I couldn't find the setting, but I did find the command to toggle the functionality and it works.

**Comment by stkb** [comment]
@adamjr27 Thanks and good to hear.

@PetrKryslUCSD Weird if you're still not finding the setting. Maybe try un/reinstalling the extension (then restarting vscode)?

**Comment by PetrKryslUCSD** [comment]
Weird, un/re installing worked. Thanks.

**Comment by stkb** [comment]
Ok well don't know why but good to hear! Will close this.
