### ISSUE TITLE
XAML files are treated like plain text

### ISSUE THREAD

**Issue by wansor** [stkb/Rewrap#263]
I use this extension in Visual Studio and cannot find a way to configure it such that XAML files are treated as XML, or at least to turn Rewrap off for these files. It's annoying that the code gets re-formatted whenever you paste somthing without turning auto wrap off first.

Anything of these features would help:
- Silently treat XAML as XML, or
- Add XAML to the list of configurable “languages”, or
- Exclude file types that rewrap shouldn't handle by specifying their extensions.

**Comment by stkb** [comment]
Yeah that XAML didn't already exist as its own type was an oversight :) I've added it now, so it will be in the next version.

I'm also looking into porting the recent feature from the VS Code version to the VS version, that lets you also configure whether auto-wrap is by default on or off per file-type.

**Comment by stkb** [comment]
Was added in v1.15.0
