### ISSUE TITLE
Rewrap on save

### ISSUE THREAD

**Issue by bishshoy** [stkb/Rewrap#267]
Can we have a setting that if toggled ON, it will rewrap the entire document when Ctrl + S is triggered?

This is helpful in situation such as Plaintext or LaTeX, where you don't want live rewrapping to distract you from the writing process, but instead you want to invoke the rewrap command using a keyboard shortcut when required.

**Comment by rdlauer** [comment]
Agreed. Sometimes I'm editing a doc and wrapping isn't applied due to the types of changes I'm making. An "on save" option would guarantee the wraps would be implemented when I'm done.

**Comment by stkb** [comment]
This is now in the latest pre-release version, but closing as a dup of #165. See the comment there.
