### ISSUE TITLE
Rewrap stopped working

### ISSUE THREAD

**Issue by neclepsio** [stkb/Rewrap#289]
Rewrap no longer works: the commands are there, but there is no effect, whatever the file type is. I'm using VSCode 1.60 and Rewrap 1.14. There is no error in developer console. It happens in both my computers, which do not share settings.

**Comment by rweickelt** [comment]
It stopped to work on Linux a while ago. Now also on Windows.

**Comment by neclepsio** [comment]
This does not seem to be the issue, the current workspace is trusted for me (but it's a global setting, not related to the extension).

**Comment by neclepsio** [comment]
I found out what the problem is: I'm trying to rewrap the text inside a '<script lang="none">' tag of an html file, which is maybe unsupported. I will open a different issue.
