### ISSUE TITLE
Default keyboard shortcut stopped working

### ISSUE THREAD

**Issue by DavidMetcalfe** [stkb/Rewrap#296]
Just posting this Issue in case any data requested by the dev(s) might be useful. When I first added the extension over the last week, the shortcut worked flawlessly, but now it does not work at all despite there being no conflicting keyboard shortcuts at the OS level or the application level. The extension has already been removed and re-added with Visual Studio Code having been restarted in between and the problem persists.

Please let me know if you require any additional information or if there are any logs I can provide.

**OS:** Mac OS 12.1 Beta (21C5021h)
**Visual Studio Code:** Version: 1.62.0 (Universal)

![image](https://user-images.githubusercontent.com/80915/140816145-f515b56f-8b8e-48ee-b591-42726d89f14b.png)

**Comment by stkb** [comment]
Hi, there wasn't any update to the extension in the time it stopped working. Does it work if you manually invoke the command palette rather than using the shortcut?

**Comment by DavidMetcalfe** [comment]
I assume so. Unfortunately (or fortunately), it's gone back to working before I was able to verify through command palette. During the time I was having issues, I was making use of the Auto Wrap as a compromise.

The only possible fix that might've resolve it is the Mac was rebooted to update to the latest Mac OS beta release, so I suspect the cause is related to the beta and not to do with the app or extension.

**Comment by sarina** [comment]
I know this is closed but adding a comment in case someone else with this problem (like I have had the past two days) comes across this: I (was) on Mac OS 12.2, tried uninstalling and reinstalling the extension a few times, restarting vscode, tried remapping the opt-q to other key combos, no luck. Pulled for updates, updated to 12.2.1 and computer restart and bam, it works again. Major shrug but hope this helps someone out.

**Comment by stkb** [comment]
@sarina Thanks for reporting; strange case indeed.
