### ISSUE TITLE
Can rewrap detect comment 'titles' if they end in a full stop

### ISSUE THREAD

**Issue by AncientSwordRage** [stkb/Rewrap#304]
I often have comments in my javascript code like this

```javascript
// This is a thing that does stuff.
//    It does does stuff that way for a variety of reasons. Maybe I need multiple sentences.
```
I've been using indenting to visually mark the title/paragraph distinction, as this isn't markdown.

But running rewrap does this:

```javascript
// This is a thing that does stuff. It does does stuff that way for a variety of 
// reasons. Maybe I need multiple sentences.
```

I know I can put `#` in front of my 'title' but I'd like an option to say like `rewrap.preserveTitleBeforeIndent`  or `rewrap.preserveTitleIfFirstParaPeriod`   ??

**Comment by stkb** [comment]
Ok there are two quick workarounds that will work for you now to preserve any line break.

The first is to add two spaces to the end of the first line. You'll have to make sure to turn off "Trim Trailing Whitespace (on save)" in VSCode though.

```javascript
// (· = space)

// This is a thing that does stuff.··
//    It does does stuff that way for a variety of 
//    reasons. Maybe I need multiple sentences.
```

The second gets around the trailing whitespace problem; you can end the line with a backslash instead:

```javascript
// This is a thing that does stuff. \
//    It does does stuff that way for a variety of 
//    reasons. Maybe I need multiple sentences.
```


I don't really want to add very specific config options like that unless more people ask for it.

However I am planning to add a feature, where you can choose the content parser for comments. Eg:
* plaintext (paragraphs separated only by blank lines)
* plaintext (paragraphs separated by indent)
* markdown
* reStructuredText
* xmldoc, etc...

*Maaybe* I could add "markdown + paragraphs separated by indent" in there too. But it really needs more support.

**Comment by stkb** [comment]
Oh also I forgot, I will be implementing #295 too (not just for LaTex), where there's the option to perserve any line break after a period. So while that doesn't deal with indents, it may also work for you.

**Comment by AncientSwordRage** [comment]
Any or all of those could work. Our linter currently shouts about trailing spaces but I'm sure I can figure it out or wait for #295.
