### ISSUE TITLE
Prisma docstrings are mangled on wrap

### ISSUE THREAD

**Issue by lostfictions** [stkb/Rewrap#306]
When writing a [Prisma](https://www.prisma.io/) schema file, which [differentiates between `//` and `///`](https://www.prisma.io/docs/concepts/components/prisma-schema#comments), Rewrap incorrectly wraps the latter form (`///`).

For example, given the following:

```prisma
/// this is the post model. it probably doesn't require much elaboration as it's fairly self-evident, but i'm going to ramble on at length about it.
model Post {
  id Int @id @default(autoincrement())
  text String
}
```

Rewrap will wrap the comment as follows:

```prisma
/// this is the post model. it probably doesn't require much elaboration as it's
//fairly self-evident, but i'm going to ramble on at length about it.
model Post {
  id Int @id @default(autoincrement())
  text String
}
```

The wrapped comment doesn't preserve the `///` syntax, and instead mangles it to `//`. The spacing between the slashes and the start of the comment is also lost.

**Comment by stkb** [comment]
Hi this should be fixed in [pre-release version 17.4](https://github.com/stkb/Rewrap/releases/beta).

**Comment by lostfictions** [comment]
Thanks for the quick response! Seems to work great with 17.4.

**Comment by stkb** [comment]
Now also in stable version 1.16.1
