### ISSUE TITLE
Rewrap marks files as modified in VS Code even if it didn't change anything

### ISSUE THREAD

**Issue by lostfictions** [stkb/Rewrap#308]
Hi again, thanks for this extension -- it's really useful and I use it all the time. One small nit I've encountered is: sometimes I'll hit the Rewrap shortcut just to check that something's been wrapped to the right length, but this always causes it to mark a file as "dirty" (changed and in need of saving) even if the action didn't change the text at all.

It's slightly confusing since I'll often absentmindedly hit the keybinding, read over some files before committing, and then get interrupted by VS Code warning me that there's unsaved changes. Then I have to stop and remember that no, I didn't actually modify anything further, Code is just a little muddled by an extension.

Not sure if the extension API offers an easy built-in way of handling this, but maybe it wouldn't be too hard to compare the block to be wrapped before and after wrapping and only apply the modification to the document if they're different?

**Comment by stkb** [comment]
> but maybe it wouldn't be too hard to compare the block to be wrapped before and after wrapping and only apply the modification to the document if they're different?

Yeah it used to do exactly this, but it got removed that when I was rewriting some stuff, with the plan of making it a bit smarter. Since it was minor I hadn't gotten around to writing its replacement yet. I'll put a fix in the next pre-release version.

**Comment by stkb** [comment]
This should now be fixed in [pre-release version 17.5](https://github.com/stkb/Rewrap/releases/tag/beta)

**Comment by stkb** [comment]
Now in stable v1.16.2.
