### ISSUE TITLE
Wrapping doesn't work on sass `//` comments in Vue SFCs

### ISSUE THREAD

**Issue by symmetriq** [stkb/Rewrap#309]
First, thank you for this incredibly useful extension! I use it constantly.

Here's the issue: Nothing happens when I try to wrap `// sass comments` in the `<style>` section of a `.vue` file. Wrapping works as expected on `/* standard CSS comments */`.

```vue
<style lang="scss">
// This is a really long comment that should definitely wrap but doesn't because wrapping is only supported for standard CSS comments

/* This comment will wrap just fine, even though it's really long and goes on for awhile, because it's a standard CSS comment. */
</style>
```

Wrapping `//` comments in regular `.scss` files works as expected.

**Comment by stkb** [comment]
Yeah it's not smart enough to look at `lang` attributes yet. I'll just add `//` comments to CSS.

**Comment by symmetriq** [comment]
That should do the trick. Thanks!

**Comment by stkb** [comment]
This should now work in [pre-release version 17.5](https://github.com/stkb/Rewrap/releases/tag/beta)

**Comment by symmetriq** [comment]
Just tried it. It works. Thanks!

**Comment by stkb** [comment]
Now in stable v1.16.2 too.
