### ISSUE TITLE
Markdown support may have stopped working in latest VS Code

### ISSUE THREAD

**Issue by robdodson** [stkb/Rewrap#31]
I noticed my alt-q command is no longer wrapping markdown text. Changing the document to Plain Text fixes the issue.

**Comment by stkb** [comment]
Hi, sorry for the long time in replying. Are you still experiencing this issue? I couldn't repro it on v1.3.0. If you like you can try the new 1.4 beta (#40)

**Comment by stkb** [comment]
Still couldn't find any problems and a new version has now been published, so I'm going to close this. Please let me know if you're still having this issue.
