### ISSUE TITLE
Batch files: support uppercase REM and @REM

### ISSUE THREAD

**Issue by eykamp** [stkb/Rewrap#313]
I'd like to know if it would be possible to add support for Windows Batch files.  It seems pretty straightforward... comments begin with "REM " or "@REM ", and there are no block comments.  If there is a way I can configure this myself, that would make me happy enough.

Thanks!

**Comment by stkb** [comment]
Hi, .bat and .cmd support is already in there but I just found that it has some bugs. It currently supports "**rem**" (lowercase) or "**::**" for comments. I need to fix it so it's case insensitive and supports the optional "**@**" too. That's easily done so a fix will be coming soon.

**Comment by eykamp** [comment]
I am observing that behavior too.  Thanks for your quick response!

It's less of an issue for me, but it also seems to be missing from the list of content types on the docs page: https://stkb.github.io/Rewrap/specs/content-types

**Comment by stkb** [comment]
This should now work in [pre-release version 17.5](https://github.com/stkb/Rewrap/releases/tag/beta).

Yeah that list of content types isn't exhaustive. In the beginning I added tests for every file type supported, but now I only add types that have some sort of special behavior to them. However I've now added tests for batch files :)

**Comment by stkb** [comment]
Now fixed in v1.16.2
