### ISSUE TITLE
Don't add to undo stack if nothing happens

### ISSUE THREAD

**Issue by eykamp** [stkb/Rewrap#315]
In VS Code, if I reformat a section, and no reformatting is needed (i.e. nothing changes), the "empty" format step should not be added to the undo/redo stack.

That is, if I type a letter, then press Alt-Q and nothing changes, when I press Ctrl-Z, the letter I typed should be undone.  Currently, I need to press Ctrl-Z twice for that to happen.

Not a major issue, just something I noticed.

**Comment by stkb** [comment]
Hi and thanks; this is the same issue as in #308, and should now be fixed in [pre-release version 17.5](https://github.com/stkb/Rewrap/releases/tag/beta)
