### ISSUE TITLE
Array prototype changes causing exceptions in other extensions

### ISSUE THREAD

**Issue by tylerb** [stkb/Rewrap#32]
Greetings!

I have been working on debugging an exception occurring in the `vscode-go` extension. I have traced it back to your extension altering the prototype for `Array`.

https://github.com/stkb/vscode-rewrap/blob/master/src/extensions.ts

Unfortunately, my knowledge of javascript is limited, so I am not sure what the appropriate solution is here. I'm opening this issue so both sides can work together to figure out an appropriate solution.

Please see Microsoft/vscode-go#915.

Thanks!

**Comment by stkb** [comment]
Hi,
It's weird because I thought extensions were isolated when it comes to this sort of thing. Anyway the next version of Rewrap won't have this code any more and since it's also been fixed on vscode-go's side, I'll close this.
