### ISSUE TITLE
Markdown front-matter section: allow characters on line after ending `---`

### ISSUE THREAD

**Issue by MikeBishop** [stkb/Rewrap#321]
Possibly introduced by #277, but rewrap won't process any lines in https://github.com/quicwg/base-drafts/blob/main/draft-ietf-quic-http.md.  After some experimentation, it appears that this goes away when the `---` is removed from the first line, suggesting that Rewrap is disabling itself in the presence of front-matter.

After reading #277, I'm wondering if Rewrap is unable to find the end of the front matter in that file, and therefore treats the entire file as front-matter?

**Comment by MikeBishop** [comment]
Confirmed that it works properly in 1.15.4.

**Comment by stkb** [comment]
Yeah markdown is great with all its different implementations.

> After reading #277, I'm wondering if Rewrap is unable to find the end of the front matter in that file, and therefore treats the entire file as front-matter?

Yep exactly this; it's looking for a line that has `---` and nothing else, so the line `--- abstract` doesn't count.

When implementing #277, I couldn't find any real spec on front matter sections, so I didn't really know what the start/end markers should exactly look like. I went with what I could gather to be correct which was just lines with `---`, with whitespace allowed after but not before, but now I see that's not always the case.

It'll be easy enough to change it to allow text content after the `---` on the line, but if you could point me to a spec for the markdown flavor that document is written in, I'd appreciate it :)

**Comment by stkb** [comment]
This is now fixed in [pre-release version 17.7](https://github.com/stkb/Rewrap/releases/beta)

**Comment by stkb** [comment]
Now in stable v1.16.3
