### ISSUE TITLE
Suggestion: Enable wrapping even if there are two (or more) leading spaces in comment block

### ISSUE THREAD

**Issue by atc0005** [stkb/Rewrap#322]
Hi,

First of all, many thanks for this awesome VSCode extension. I really appreciate how flexible it is and consider it a core part of my editor experience.

Scenario:

```golang
	//  The Mention object has two properties that you must set using the following:
	//
	// Include @username in the message text. Include the mention object
	// inside the entities collection.
```

I select all three lines and trigger a `Rewrap Comment / Text` operation. Nothing happens. Note that there are two spaces between `//` and `The Mention object has two`. 

If I reduce the spaces to just one and trigger a `Rewrap Comment / Text` operation, then this is the (expected) result:

```golang
	// The Mention object has two properties that you must set using the
	// following:
	//
	// Include @username in the message text. Include the mention object
	// inside the entities collection.
```

I'm not sure if this is a bug, or expected behavior for the plugin.

Details:

- Rewrap `v1.16.2`
- Visual Studio Code `v1.64.2`

**Comment by stkb** [comment]
Hi, I noticed that you're using golang. Golang comments are parsed by the extension as [godoc](https://go.dev/blog/godoc) where any indented lines are "preserved text" so not wrapped.

I do intend on making the content type for comments configurable in the near future though.

**Comment by atc0005** [comment]
Ah, I see the challenge then. Sounds like this was just ignorance on my part. Thanks for the explanation!
