### ISSUE TITLE
Feature request: Dart support

### ISSUE THREAD

**Issue by nyc** [stkb/Rewrap#33]
The comment format is pretty much the same as Java/C/C++.

```dart
// Inline comments
/// DartDoc comments
/** Also valid DartDoc comments */
```

[Source](https://www.dartlang.org/guides/language/effective-dart/documentation)

**Comment by stkb** [comment]
Hi, sorry this took a while but I've added Dart support to the next version (#40). One thing missing though in that beta version is support for template and macro tags; I'll try to get that in before release.

**Comment by stkb** [comment]
Version 1.4 has now been published and supports the nodoc, template and macro tags. Let me know if there are still issues!
