### ISSUE TITLE
Do not break inline tags like {@link }

### ISSUE THREAD

**Issue by billccn** [stkb/Rewrap#35]
JSDoc3 inline tags are `{@link} (synonyms: {@linkcode}, {@linkplain})` and `{@tutorial}`, but should probably expand to all tags of the form `{@ ... }`

**Comment by stkb** [comment]
Hi, just to make sure I understand correctly, you're saying the whole contents of a {@x ... } tag should be kept on one line?

**Comment by stkb** [comment]
This is now in v1.4.0. Please let me know if you still have issues!
