### ISSUE TITLE
Visual Studio equivalent to Rewrap?

### ISSUE THREAD

**Issue by harefoot55** [stkb/Rewrap#36]
Is there a Visual Studio equivalent to Rewrap? This looks great but I don't use VS Code. I would love to have this functionality in Visual Studio 2015.

**Comment by stkb** [comment]
Hi! Yeah I missed this in Visual Studio too, so I'm working on a VS extension. Please see #40 for details of the beta.

**Comment by harefoot55** [comment]
Thanks for letting me know!
