### ISSUE TITLE
feature request: protobuf support

### ISSUE THREAD

**Issue by glerchundi** [stkb/Rewrap#47]
Is it possible to have protocol buffers support?

Thanks!

**Comment by stkb** [comment]
Thanks for the request! Will publish the addition this weekend

**Comment by glerchundi** [comment]
Wow! Very much appreciated 👏🏻

**Comment by stkb** [comment]
Now in v1.5.1. Let me know if you have any problems

**Comment by glerchundi** [comment]
Updated & working as expected. Thanks
