### ISSUE TITLE
\0 replaced with <space> during rewrap

### ISSUE THREAD

**Issue by jstarks** [stkb/Rewrap#48]
Rewrap 1.5.0. Put this in a text file:

    foo\0bar\0baz

After Alt-Q:

    foo bar baz

Just to be clear, I'm not talking about actual embedded NUL bytes, I mean instances of the literal string "\0" (backslash zero) are being replaced with what appear to be space characters.

Very strange!

**Comment by stkb** [comment]
Thanks for the catch! Yeah it was supposed to be using NUL characters as placeholders which are later replaced with spaces. Turns out the F# literal for those is different from in C* or JS.

**Comment by stkb** [comment]
Should now be fixed in v1.5.1. Let me know if you have any problems
