### ISSUE TITLE
Wrapping string literals in Java

### ISSUE THREAD

**Issue by TheIndifferent** [stkb/Rewrap#51]
With https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack + Rewrap installed, following code:
```
  private void checkState() {
    if (job == null) {
      throw new IllegalStateException("Job was not initialized, deploy() has to be invoked or failed the invocation");
    }
  }
```

Gets rewrapped to following:
```
  private void checkState() {
    if (job == null) {
      throw new IllegalStateException("Job was not initialized, deploy() has to
      be invoked or failed the invocation");
    }
  }
```

**Comment by stkb** [comment]
It's not directly intended. Seems to be the same issue as in #41 (see my comment there).

I'm probably going to remove that behavior, as it seems to be more confusing than helpful.

**Comment by stkb** [comment]
Shouldn't happen any more in v1.6.0
