### ISSUE TITLE
* at the start of each line not really working

### ISSUE THREAD

**Issue by jcredland** [stkb/Rewrap#52]
Reformatting comments such as this doesn't work.  It needs to identify that every line begins with a start and insert one at the start of the line when wrapping etc.

```
	/**
	 * Returns the number of samples that can be read, and a pointer where you 
	 * can start reading the samples.  Two calls may be necessary as the samples
	 * to be read might wrap around in memory.
	 * 
	 * This call doesn't copy the samples to a new buffer so is more efficent for
	 * some tasks, e.g. metering, where you just want to calculate a value from 
	 * the available data.  
	*
	* @returns the number of samples, per channel.
	 */
```

**Comment by jcredland** [comment]
Currently the output when rewrapping this is: 
```
	/**
	 * Returns the number of samples that can be read, and a pointer where you 
	 * can start reading the samples.  Two calls may be necessary as the samples
	 * to be read might wrap around in memory.
	 * 
	 * This call doesn't copy the samples to a new buffer so is more efficent
	   for
	 * some tasks, e.g. metering, where you just want to calculate a value from 
	 * the available data.   
     *
	 * @returns the number of samples, per channel.
	 */

```

The expected output is this: 
```
	/**
	 * Returns the number of samples that can be read, and a pointer where you 
	 * can start reading the samples.  Two calls may be necessary as the samples
	 * to be read might wrap around in memory.
	 * 
	 * This call doesn't copy the samples to a new buffer so is more efficent
	 * for some tasks, e.g. metering, where you just want to calculate a value 
	 * from the available data.   
     *
	 * @returns the number of samples, per channel.
	 */

```

**Comment by stkb** [comment]
BTW thanks for the review for the Visual Studio version. Could you open another issue for the other problem you mentioned (indents increasing each time)?

**Comment by jcredland** [comment]
I'm working in C++ files.

**Comment by stkb** [comment]
Thanks. I've published an update (1.5.2) that supports this in all c-style languages. It should work as expected now.

Just curious, what documentation tool do you use?

**Comment by jcredland** [comment]
The markup is for doxygen if that’s what you mean..?

**Comment by jcredland** [comment]
Ps.  thanks for the super-prompt fix.  I’ll upgrade :)

**Comment by stkb** [comment]
Doxygen yeah thanks. I wasn't farmiliar with it but from a quick look at the docs it seems I'll need to do a couple of things to better support it. Firstly, it supports `/*!` or `//!` comment markers (I'll need to support them too). Also it seems you can use latex-style \tags as an alternative to @tags (currently only the latter is supported).

**Comment by stkb** [comment]
Thanks for the updated review :) Glad it's now working.
