### ISSUE TITLE
Indenting issue

### ISSUE THREAD

**Issue by jcredland** [stkb/Rewrap#53]
![image](https://user-images.githubusercontent.com/6928506/31331139-2673d0da-acd9-11e7-8d04-8c7ff2c20b59.png)

Pressing rewrap on this paragraph results in this output, which looks correct:

![image](https://user-images.githubusercontent.com/6928506/31331171-4191810a-acd9-11e7-9a42-973bdb04af5c.png)
 Pressing rewrap again, results in this obviously incorrect example:

![image](https://user-images.githubusercontent.com/6928506/31331193-5366c8f4-acd9-11e7-98f4-624b99e00cc9.png)

And further presses continue to increase the indent of the 2nd to 4th lines.

**Comment by stkb** [comment]
Closing in favor of #58
