### ISSUE TITLE
Error in 1.6.0-beta1

### ISSUE THREAD

**Issue by gwf** [stkb/Rewrap#59]
While editing a LaTeX file with the experimental auto-fill mode enabled, virtually all actions trigger the error (typing a line beyond the limit, hitting space mid-paragraph, hitting alt-q, etc.).

![image](https://user-images.githubusercontent.com/489848/33245391-0e23c5ea-d2bc-11e7-83dd-eb8c04ded5a0.png)

**Comment by stkb** [comment]
Fixed in beta2
