### ISSUE TITLE
Support for D language

### ISSUE THREAD

**Issue by biozic** [stkb/Rewrap#60]
This is en enhancement request to support the [D programming language](https://dlang.org). Since it's a C-based language, there are C-like comments:
```d
// This is a line comment
/* This is a block comment */
void main() {}
```

But you might also consider handling D's additions: 

-  documentation comments:
```d
/// This is a documentation line comment
/** This is a documentation block comment */
void main() {}
```

-  nested comments (obviously, not all syntax highlighters handle them!):
```d
/+
This is a comment [...]
  /+ This is a nested comment +/
[...]
+/
void main() {}
```

**Comment by stkb** [comment]
Thanks for all the info. Basic support is now in v1.6.0.

Things may not yet work perfectly in doc-comments. For that I've created #66. Workarounds in the mean time, are to use the `wholeComment: false` setting ([VS](https://github.com/stkb/Rewrap/wiki/Settings-Visual-Studio#wrapping-whole-or-parts-of-comments) | [VSCode](https://github.com/stkb/Rewrap/wiki/Settings-VSCode#wrapping-whole-or-parts-of-comments)), or to add two spaces to the end of a line to preserve a line break after it.

Nested comments unfortunately aren't supported.

**Comment by biozic** [comment]
That's great, thanks! Using `wholeComment: false` already does a good job for me.
