### ISSUE TITLE
C/C++ comment blocks with indented lines

### ISSUE THREAD

**Issue by buai** [stkb/Rewrap#64]
I attempted to rewrap a comment block where one line in the center of the block was a little too long.  It works fine normally, but if the line in question is indented too much, it does not rewrap it.  Is this a feature or a bug?  Ex: 

```
/**
 * @brief 
 * 
 *      This is a really long comment line in a doxygen block describing one of my functions.  Somtimes I get carried away
 * and forget to start a new line until it's too late. 
 * 
 * @param q 
 * @param start 
 * @return const char* 
 */
```

**Comment by stkb** [comment]
Hi, this is a feature: the content of all comments is parsed as markdown. Anything indented 4 spaces or more is treated as a [code block](http://spec.commonmark.org/0.28/#indented-code-blocks), where the lines aren't wrapped.

There may still be improvements I can make to doxygen support however, so let me know if you come across anything else.

**Comment by buai** [comment]
Thanks for the rundown, stkb. It makes sense to me.
