### ISSUE TITLE
Wrapping verbatim environment in latex documents

### ISSUE THREAD

**Issue by urob** [stkb/Rewrap#68]
First, thanks for a great extension!

One small suggestion for latex documents: I think it would make sense to exclude verbatim environments from being wrapped, as they are sensitive to line breaks. 

(In my case I re-wrapped a long document and only noticed later that this destroyed a few verbatim environments that were scattered throughout)

**Comment by stkb** [comment]
Hi, thanks for the kind words

I try to support LaTeX as fully as possible but I don't use it myself which is why things like this get missed (until people report them).
This shouldn't be a problem to add.

**Comment by urob** [comment]
Thanks, this would be great!

**Comment by stkb** [comment]
I've just added this feature. I'd like to fix some other issues before publishing the next version in a week's time.

However if you'd like to test it sooner, you can download/install the beta version which has this change, from https://github.com/stkb/Rewrap/releases/tag/v1.7.0-beta1

**Comment by urob** [comment]
Just tried it out: Works great! Thanks so much for the quick fix!

**Comment by stkb** [comment]
Now in v1.7.0... closing
