### ISSUE TITLE
Not wrapping matlab files

### ISSUE THREAD

**Issue by garyballantyne** [stkb/Rewrap#72]
Many thanks for Rewrap. With vscode 1.19.3 and Rewrap 1.6.1, I can't get text to wrap for either in-line comments (i.e., beginning with %) or block comments (%{ ... %}) for matlab (.m) files. For an ordinary text file (.txt) it appears fine. Vscode seems to note something has happened, as Alt-Q triggers the unsaved file notification--but I can't see any actual difference in the text.

I have the matlab extension (0.80, Xavier Hahn) installed, but removing it made no difference. 

I have tried both Alt-Q and via F1.

**Comment by stkb** [comment]
Hi, Matlab isn't supported yet; I need to add it :)

I was just reading [the docs](http://nl.mathworks.com/help/matlab/matlab_prog/comments.html). Is it correct that comment lines beginning with two '%'s (code section titles) should not be wrapped?

**Comment by garyballantyne** [comment]
I have been using with matlab/octave for a while--must have just been lucky I guess :-)

I don't use the %% thing, and it doesn't seem supported in vscode (at least, in the extension mentioned above). 

In matlab's own editor %% provides some highlighting (and perhaps even folding in more recent versions). However, neither of the two options below for wrapping a section heading appear to work. The first option creates two sections, and the second option is just a comment following the section heading. So, I guess the short answer is that %% lines shouldn't be wrapped.

%% this is a section
%% this is a wrapped part

%% this is another code section
% this is another wrapped part

**Comment by stkb** [comment]
Thanks! That was exactly what I needed to know.

**Comment by stkb** [comment]
This will be in the next version, releasing this weekend.

Note: you will need the extension instaled for wrapping to work (since without it, vscode marks .m files as Objective-C)

**Comment by garyballantyne** [comment]
Great! Thanks very much.

**Comment by stkb** [comment]
Now in v1.7.0. Closing, but let me know if anything's not working.

**Comment by garyballantyne** [comment]
I had a quick look, and its working well. Thanks again.
