### ISSUE TITLE
Support for Elixir's @doc and @moduledoc

### ISSUE THREAD

**Issue by seanwash** [stkb/Rewrap#76]
I've looked through the wiki and issues and haven't noticed anything mentioning Elixir's `@doc` or `@moduledoc` blocks. Is there a setting for this or are these blocks not supported?

Ex:

```elixir
defmodule Math do
  @moduledoc """
  Provides math-related functions.

  ## Examples

      iex> Math.sum(1, 2)
      3

  """

  @doc """
  Calculates the sum of two numbers.
  """
  def sum(a, b), do: a + b
end
```

**Comment by stkb** [comment]
Hi, this is not supported yet. I'll try to get a beta out with support soon!

**Comment by stkb** [comment]
I've added it and it'll be in the next version. Not sure when that will be released; if you'd like to test the beta version, it can be downloaded from https://github.com/stkb/Rewrap/releases/tag/v1.8.0-beta1

**Comment by seanwash** [comment]
Thanks @stkb! Any way I can send you some beer money for this?

**Comment by stkb** [comment]
Hey that's very kind of you! But contented users are enough for me 👍

**Comment by seanwash** [comment]
@stkb works like a charm! Thanks!
