### ISSUE TITLE
Nested lists in Markdown are not wrapped when indented by more than 2 spaces

### ISSUE THREAD

**Issue by joliss** [stkb/Rewrap#79]
With Rewrap 1.7.1, the following Markdown text does not seem to get rewrapped correctly:

```md
* Nested list:

    * This is a very very very very very very very very very very very very very long line

    * This is a very very very very very very very very very very very very very long line
```

Pressing Alt+q on the nested list items only rewraps the first. Nothing happens if I try to rewrap the second.

```md
* Nested list:

    * This is a very very very very very very very very very very very very very
      long line

    * This is a very very very very very very very very very very very very very long line
```

This also happens for numbered lists (`1.`, `2.`).

It only happens when the nested list is indented 4 spaces, rather than 2.

**Comment by joliss** [comment]
Update: Even with 2-space indentation, the same issue happens with lists nested two levels deep:

```md
* Nested list

  * Nested list:

    * This is a very very very very very very very very very very very very very long line

    * This is a very very very very very very very very very very very very very long line
```

Again, only the first item will be wrapped by Rewrap.

**Comment by stkb** [comment]
Thanks for the explanation and sorry I didn't get back to you sooner. I'll work on fixing this, but meanwhile, as workaround, it works if you remove the blank lines between list items.

I.e: the last item will wrap in this case:

```
* Nested list

  * Nested list:

    * This is a very very very very very very very very very very very very very long line
    * This is a very very very very very very very very very very very very very long line
````

**Comment by stkb** [comment]
Ok never mind the workaround, I think I've fixed it, and have uploaded a beta version. You can try it from https://github.com/stkb/Rewrap/releases/tag/v1.8.0-beta2.

Let me know if you discover any other markdown bugs; I'm currently working on another subtle one.

**Comment by joliss** [comment]
Works great, thank you for the fix!

(Not sure if you were keeping this issue open for a reason; I'll leave it to you to close it.)

**Comment by stkb** [comment]
Thanks! Will close when I publish the next version, which should be this weekend.
