### ISSUE TITLE
Support for Vue Single File Components (SFCs)

### ISSUE THREAD

**Issue by benlind** [stkb/Rewrap#82]
Rewrap does not wrap comments correctly when they are in the `<script>` section of Vue Single File Components.

If I have this file:

```
// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum nisi ac viverra eleifend.
console.log('These lines')
console.log('have the same')
console.log('indentation level')
```

...and execute Rewrap with my cursor in the comment, I get:

```
// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum nisi
ac viverra eleifend. console.log('These lines') console.log('have the same')
console.log('indentation level')
```

Rewrap wraps any code on the same indentation level with the comment. And it doesn't add `//` before each line.

It would be great if this was supported. Thanks!

**Comment by stkb** [comment]
Yeah this is just what happens when the document type isn't supported. I'll take it a look at this tomorrow but I think it should be easy.

**Comment by stkb** [comment]
Hi, could you try downloading & installing the latest beta version from https://github.com/stkb/Rewrap/releases/tag/v1.8.1-beta1? Thanks!

**Comment by benlind** [comment]
Looks like it's working perfectly. Thanks for the quick work!

**Comment by stkb** [comment]
Great! Thanks.
