### ISSUE TITLE
Wrapping Column change requires restart to take effect

### ISSUE THREAD

**Issue by GabeChiarelli** [stkb/Rewrap#99]
IDE: VS 2015 Professional

Changes to Wrapping Column value do not take effect until full IDE restart. Not necessarily a bug, but I couldn't find it documented anywhere and was unexpected. Works fine after restarting.

**Comment by stkb** [comment]
This will be fixed in the next version, released probably this weekend. If you want to test it out now, you can [try the latest beta version](https://github.com/stkb/Rewrap/releases/tag/beta)
